// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MessageMetadataMessageType.
const (
	RocketExploded       MessageMetadataMessageType = "RocketExploded"
	RocketLaunched       MessageMetadataMessageType = "RocketLaunched"
	RocketMissionChanged MessageMetadataMessageType = "RocketMissionChanged"
	RocketSpeedDecreased MessageMetadataMessageType = "RocketSpeedDecreased"
	RocketSpeedIncreased MessageMetadataMessageType = "RocketSpeedIncreased"
)

// Defines values for RocketStatus.
const (
	Active   RocketStatus = "active"
	Exploded RocketStatus = "exploded"
)

// Defines values for ListRocketsParamsSortBy.
const (
	Channel ListRocketsParamsSortBy = "channel"
	Mission ListRocketsParamsSortBy = "mission"
	Speed   ListRocketsParamsSortBy = "speed"
	Status  ListRocketsParamsSortBy = "status"
	Type    ListRocketsParamsSortBy = "type"
)

// Defines values for ListRocketsParamsOrder.
const (
	Asc  ListRocketsParamsOrder = "asc"
	Desc ListRocketsParamsOrder = "desc"
)

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// MessageMetadata defines model for MessageMetadata.
type MessageMetadata struct {
	// Channel Unique channel ID for the rocket
	Channel openapi_types.UUID `json:"channel"`

	// MessageNumber Order of the message within a channel
	MessageNumber int `json:"messageNumber"`

	// MessageTime When the message was sent
	MessageTime time.Time                  `json:"messageTime"`
	MessageType MessageMetadataMessageType `json:"messageType"`
}

// MessageMetadataMessageType defines model for MessageMetadata.MessageType.
type MessageMetadataMessageType string

// Rocket defines model for Rocket.
type Rocket struct {
	// Channel Unique channel ID for the rocket
	Channel openapi_types.UUID `json:"channel"`

	// ExplosionReason Reason for explosion (if status is exploded)
	ExplosionReason *string `json:"explosionReason,omitempty"`

	// LastMessageNumber Last processed message number
	LastMessageNumber *int `json:"lastMessageNumber,omitempty"`

	// LastMessageTime Time of last processed message
	LastMessageTime *time.Time `json:"lastMessageTime,omitempty"`

	// Mission Current mission name
	Mission string `json:"mission"`

	// Speed Current speed of the rocket
	Speed int `json:"speed"`

	// Status Current status of the rocket
	Status RocketStatus `json:"status"`

	// Type Type of rocket
	Type string `json:"type"`
}

// RocketStatus Current status of the rocket
type RocketStatus string

// RocketExplodedPayload defines model for RocketExplodedPayload.
type RocketExplodedPayload struct {
	// Reason Reason for explosion
	Reason string `json:"reason"`
}

// RocketLaunchedPayload defines model for RocketLaunchedPayload.
type RocketLaunchedPayload struct {
	// LaunchSpeed Initial launch speed
	LaunchSpeed int `json:"launchSpeed"`

	// Mission Mission name
	Mission string `json:"mission"`

	// Type Type of rocket
	Type string `json:"type"`
}

// RocketMessage defines model for RocketMessage.
type RocketMessage struct {
	Message  RocketMessage_Message `json:"message"`
	Metadata MessageMetadata       `json:"metadata"`
}

// RocketMessage_Message defines model for RocketMessage.Message.
type RocketMessage_Message struct {
	union json.RawMessage
}

// RocketMissionChangedPayload defines model for RocketMissionChangedPayload.
type RocketMissionChangedPayload struct {
	// NewMission New mission name
	NewMission string `json:"newMission"`
}

// RocketSpeedDecreasedPayload defines model for RocketSpeedDecreasedPayload.
type RocketSpeedDecreasedPayload struct {
	// By Amount by which speed decreased
	By int `json:"by"`
}

// RocketSpeedIncreasedPayload defines model for RocketSpeedIncreasedPayload.
type RocketSpeedIncreasedPayload struct {
	// By Amount by which speed increased
	By int `json:"by"`
}

// ListRocketsParams defines parameters for ListRockets.
type ListRocketsParams struct {
	// SortBy Field to sort by
	SortBy *ListRocketsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// Order Sort order
	Order *ListRocketsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListRocketsParamsSortBy defines parameters for ListRockets.
type ListRocketsParamsSortBy string

// ListRocketsParamsOrder defines parameters for ListRockets.
type ListRocketsParamsOrder string

// PostMessageJSONRequestBody defines body for PostMessage for application/json ContentType.
type PostMessageJSONRequestBody = RocketMessage

// AsRocketLaunchedPayload returns the union data inside the RocketMessage_Message as a RocketLaunchedPayload
func (t RocketMessage_Message) AsRocketLaunchedPayload() (RocketLaunchedPayload, error) {
	var body RocketLaunchedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRocketLaunchedPayload overwrites any union data inside the RocketMessage_Message as the provided RocketLaunchedPayload
func (t *RocketMessage_Message) FromRocketLaunchedPayload(v RocketLaunchedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRocketLaunchedPayload performs a merge with any union data inside the RocketMessage_Message, using the provided RocketLaunchedPayload
func (t *RocketMessage_Message) MergeRocketLaunchedPayload(v RocketLaunchedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRocketSpeedIncreasedPayload returns the union data inside the RocketMessage_Message as a RocketSpeedIncreasedPayload
func (t RocketMessage_Message) AsRocketSpeedIncreasedPayload() (RocketSpeedIncreasedPayload, error) {
	var body RocketSpeedIncreasedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRocketSpeedIncreasedPayload overwrites any union data inside the RocketMessage_Message as the provided RocketSpeedIncreasedPayload
func (t *RocketMessage_Message) FromRocketSpeedIncreasedPayload(v RocketSpeedIncreasedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRocketSpeedIncreasedPayload performs a merge with any union data inside the RocketMessage_Message, using the provided RocketSpeedIncreasedPayload
func (t *RocketMessage_Message) MergeRocketSpeedIncreasedPayload(v RocketSpeedIncreasedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRocketSpeedDecreasedPayload returns the union data inside the RocketMessage_Message as a RocketSpeedDecreasedPayload
func (t RocketMessage_Message) AsRocketSpeedDecreasedPayload() (RocketSpeedDecreasedPayload, error) {
	var body RocketSpeedDecreasedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRocketSpeedDecreasedPayload overwrites any union data inside the RocketMessage_Message as the provided RocketSpeedDecreasedPayload
func (t *RocketMessage_Message) FromRocketSpeedDecreasedPayload(v RocketSpeedDecreasedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRocketSpeedDecreasedPayload performs a merge with any union data inside the RocketMessage_Message, using the provided RocketSpeedDecreasedPayload
func (t *RocketMessage_Message) MergeRocketSpeedDecreasedPayload(v RocketSpeedDecreasedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRocketExplodedPayload returns the union data inside the RocketMessage_Message as a RocketExplodedPayload
func (t RocketMessage_Message) AsRocketExplodedPayload() (RocketExplodedPayload, error) {
	var body RocketExplodedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRocketExplodedPayload overwrites any union data inside the RocketMessage_Message as the provided RocketExplodedPayload
func (t *RocketMessage_Message) FromRocketExplodedPayload(v RocketExplodedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRocketExplodedPayload performs a merge with any union data inside the RocketMessage_Message, using the provided RocketExplodedPayload
func (t *RocketMessage_Message) MergeRocketExplodedPayload(v RocketExplodedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRocketMissionChangedPayload returns the union data inside the RocketMessage_Message as a RocketMissionChangedPayload
func (t RocketMessage_Message) AsRocketMissionChangedPayload() (RocketMissionChangedPayload, error) {
	var body RocketMissionChangedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRocketMissionChangedPayload overwrites any union data inside the RocketMessage_Message as the provided RocketMissionChangedPayload
func (t *RocketMessage_Message) FromRocketMissionChangedPayload(v RocketMissionChangedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRocketMissionChangedPayload performs a merge with any union data inside the RocketMessage_Message, using the provided RocketMissionChangedPayload
func (t *RocketMessage_Message) MergeRocketMissionChangedPayload(v RocketMissionChangedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RocketMessage_Message) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RocketMessage_Message) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
